kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: metadata-service
  namespace: metadata-service
spec:
  selector:
    matchLabels:
      k8s-app: metadata-service
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: metadata-service
    spec:
      restartPolicy: Always
      serviceAccountName: privileged-metadata-sa
      hostNetwork: true
      containers:
        - resources:
            requests:
              cpu: 50m
              memory: 70Mi
          terminationMessagePath: /dev/termination-log
          name: metadata-service
          ports:
            - name: metadata
              containerPort: 16261
              protocol: TCP
          # imagePullPolicy: IfNotPresent
          imagePullPolicy: Always
          image: quay.io/mooyeg/metadata-tool:1.0
          env:
            - name: APP_CONFIG
              value: "gunicorn.conf"
            - name: APP_MODULE
              value: "main:app"
