apiVersion: v1
kind: Service
metadata:
  name: metadata-service
  namespace: metadata-service
spec:
  selector:
    k8s-app: metadata-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 16261
  internalTrafficPolicy: Local
