apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: edit-privileged-sa
  namespace: metadata-service
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: privileged-sa
  namespace: metadata-service
